Changing struct of packages dir mainly
1. Move functions to pk-common instead of standalone files
2. Structureg of /build/packages is
	package/
		desc
		vers
		package-version.tar.bz2
instead of
	package-version.tar.bz2
	package-version.vers
	package-version.desc

diff --git a/bin/cygwin/pk-common b/bin/cygwin/pk-common
--- a/bin/cygwin/pk-common
+++ b/bin/cygwin/pk-common
@@ -129,7 +129,12 @@ CODE
 
 pk-setup-status()
 {
-  ls "$INSTALL_PATH" | grep "$1" >/dev/null
+  [ -d "$INSTALL_PATH/"$1 ]
+}
+
+pk-install-status()
+{
+  [ -f "$pk_list_dir/$1.list" ]
 }
 
 pk-setup-package()
@@ -141,13 +146,14 @@ pk-setup-package()
   # find package description
   pk-find-desc "$pkg" > "$tmp_desc"
   declare ver2=`awk '/^version: / { print $2; exit }' "$tmp_desc"`
-  declare file2="$pkg-$ver2.tar.bz2"
-  declare desc2="$pkg-$ver2.desc"
+  declare file2="$pkg/$pkg-$ver2.tar.bz2"
+  declare desc2="$pkg/desc"
   declare path2=`awk '/^install: / { print $2; exit }' "$tmp_desc"`
 
+  [ -d "$pkg" ] || mkdir "$pkg"
   # download new version
-  cp "../mirror/$file2" .
-  # wget -q "$pk_find_desc_mirror/$path2"
+  cp "../mirror/$file2" "$file2"
+  # wget -q -O "$file2" "$pk_find_desc_mirror/$path2"
   cp "$tmp_desc" "$desc2"
 
   # check the md5
@@ -200,6 +206,7 @@ pk-make-dep-list2()
     declare dep
     for dep in `"$find_fun" "$1" | pk-print-deps`
     do
+      # echo "$dep" >&2
       grep "$dep" "$MINGW_BASE" >&/dev/null && continue
       add_deps "$dep"
     done
@@ -218,7 +225,7 @@ pk-check-package()
   declare pkg="$1"
   declare tab="$2"
 
-  declare file=`find . -name "$pkg*.vers"`
+  declare file="$pkg/vers"
   declare tab2="$tab  "
 
   declare tmp_diff=`pk-make-tmp`
@@ -241,4 +248,78 @@ pk-check-package()
     return 1
   }
   return 0
+}
+
+pk-local-desc()
+{
+  cat "$INSTALL_PATH/$1/desc"
+}
+
+pk-pkg-to-tar()
+{
+  declare ver=`pk-local-desc "$name" | pk-print-ver`
+  echo "$1-$ver.tar.bz2"
+}
+
+pk-local-tar()
+{
+  declare ver=`pk-local-desc "$name" | pk-print-ver`
+  echo "$1/$1-$ver.tar.bz2"
+}
+
+pk-check-clash2()
+{
+  declare name="$1"
+  declare dir="$2"
+
+  declare build_dir="$dir/"`pk-root-dir "$dir"`
+  declare file=`pk-local-tar "$name"`
+
+  declare tmp_clash=`pk-make-tmp`
+  declare tmp_files=`pk-make-tmp`
+
+  tar tj --transform="s,$MINGW_PATH2,.," --show-transformed-names \
+    -f "$INSTALL_PATH/$file" > "$tmp_files"
+
+  for name2 in $dir/list/*
+  do
+    # set intersection
+    comm -12 <(sort "$tmp_files") <(sort "$name2") > "$tmp_clash"
+    [ -s "$tmp_clash" ] && {
+      echo "ERROR: package $name clash with $name2"
+      echo "       clashed files are:"
+      cat "$tmp_clash"
+      exit 1
+    }
+  done
+  return 0
+}
+
+pk-extract2()
+{
+  declare name="$1"
+  declare dir="$2"
+
+  declare list="$dir/list/$name.list"
+  declare file=`pk-local-tar "$name"`
+  declare build_dir="$dir/"`pk-root-dir "$dir"`
+
+  pushd "$build_dir" >/dev/null
+
+  # extract package removing mingw prefix of filenames
+  declare tmp_list=`pk-make-tmp`
+  tar vxj --transform="s,$MINGW_PATH2,.," --show-transformed-names -f "$INSTALL_PATH/$file" \
+    --wildcards "$MINGW_PATH2/*" > "$tmp_list" 2>/dev/null || echo >/dev/null # nop
+
+  # rm pure directory entries
+  comm -23 <(sort "$tmp_list") <(find . -type d | sort) > "$list"
+
+  #fix .la and .pc files
+  declare file
+  grep -l "$MINGW_PATH" lib/pkgconfig/*.pc /lib/*.la | while read file
+  do
+    sed -i -re "s,$MINGW_PATH,$build_dir,g" $file
+  done
+
+  popd >/dev/null
 }
diff --git a/bin/cygwin/pk-install b/bin/cygwin/pk-install
--- a/bin/cygwin/pk-install
+++ b/bin/cygwin/pk-install
@@ -4,24 +4,28 @@ set -e
 
 . pk-common
 
-package="$1"
+name="$1"
 dir=`pk-build-dir "$2"`
 
+[ "$dir" != "/build" ] && pk-create-local-dirs "$dir"
 echo "Target dir is $dir"
 
-[ $dir" != /build" ] && pk-create-local-dirs "$dir"
+[ -z "$name" ] && { echo "ERROR: package not specified"; exit 1; }
 
-[ -z "$package" ] && { echo "ERROR: package not specified"; exit 1; }
-name=`pk-find-fun "$package" "$INSTALL_PATH" "tar.bz2"`
-
+pk_list_dir="$dir/list"
 tmp_deps=`pk-make-tmp`
-pk-check-installed "$name" "$dir"
-pk-make-dep-list "$name" "$dir" > "$tmp_deps"
+pk-make-dep-list2 "$name" pk-local-desc pk-install-status > "$tmp_deps"
+
 cat "$tmp_deps" | while read name
 do
-  file="$INSTALL_PATH/$name.tar.bz2"
-  pk-check-clash "$name" "$dir"
+  pk-check-clash2 "$name" "$dir"
   echo "install $name"
-  pk-extract "$name" "$dir"
-  [ "$dir" != "/build" ] && cp "$INSTALL_PATH/$name.tar.bz2" "$dir/packages"
+  pk-extract2 "$name" "$dir"
+  file=`pk-local-tar "$name"`
+  [ "$dir" != "/build" ] &&  {
+    mkdir "$dir/packages/$name"
+    cp -r "$INSTALL_PATH/$name"/{desc,*.tar.bz2} "$dir/packages/$name"
+  }
 done
+
+[ -s "$tmp_deps" ] || echo "Everything is installed"
diff --git a/bin/cygwin/pk-rm b/bin/cygwin/pk-rm
--- a/bin/cygwin/pk-rm
+++ b/bin/cygwin/pk-rm
@@ -4,16 +4,14 @@ set -e
 
 . pk-common
 
-package="$1"
+name="$1"
 dir=`pk-build-dir "$2"`
 
 echo "Target dir is $dir"
 
 build_dir="$dir/"`pk-root-dir "$dir"`
 
-[ -z "$package" ] && { echo "ERROR: package not specified"; exit 1; }
-
-name=`pk-find-fun "$package" "$dir/list" "list"`
+[ -z "$name" ] && { echo "ERROR: package not specified"; exit 1; }
 
 echo "remove $name"
 
@@ -24,4 +22,5 @@ rm `cat "$list_file"`
 rm "$list_file"
 
 # rm package from local dir if needed
-[ "$dir" != "/build" ] && rm "$dir/packages/$name.tar.bz2"
+file=`pk-pkg-to-tar "$name"`
+[ "$dir" != "/build" ] && rm "$dir/packages/$file"
