New pk-check and pk-setup, pk-update changed
New features of pk-update
1. Flat structure of packages
2. Refactoring

diff --git a/bin/cygwin/pk-common b/bin/cygwin/pk-common
--- a/bin/cygwin/pk-common
+++ b/bin/cygwin/pk-common
@@ -77,3 +77,168 @@ pk-root-dir()
     echo "libs"
   fi
 }
+
+# $1 - .tar.bz file
+# $2 - package name
+pk-get-ver()
+{
+  declare a
+  a=${1%.tar.bz2}
+  echo "${a#$2-}"
+}
+
+pk-find-desc()
+{
+  declare pkg="$1"
+  set +e
+  # find package description
+  declare mirror
+  for mirror in "$MIRROR_MAIN" "$MIRROR_PORTS"
+  do
+    declare dir="/setup/`pk-mirror-dir "$mirror"`"
+    tmp_script=`pk-make-tmp`
+    cat >"$tmp_script" - <<'CODE'
+      BEGIN {
+        RS = "\n\n@ "
+        FS = "\n"
+      }
+      {
+        if ($1 == package) {
+          desc = $0
+          px++
+        }
+      }
+      END {
+        if (px == 1 && desc != "")
+          print desc
+        else
+          exit 1
+      }
+CODE
+  # cat "$tmp_script" >&2
+  awk -v package="$pkg" -f "$tmp_script" "$dir/setup.ini" && {
+    set -e
+    pk_find_desc_mirror="$mirror"
+    return
+  }
+  done
+  set -e
+  echo "ERROR: $pkg not found in mirrors" >&2
+  exit 1
+}
+
+pk-setup-status()
+{
+  ls "$INSTALL_PATH" | grep "$1" >/dev/null
+}
+
+pk-setup-package()
+{
+  declare pkg="$1"
+  declare tmp_desc=`pk-make-tmp`
+  declare tmp_deps=`pk-make-tmp`
+
+  # find package description
+  pk-find-desc "$pkg" > "$tmp_desc"
+  declare ver2=`awk '/^version: / { print $2; exit }' "$tmp_desc"`
+  declare file2="$pkg-$ver2.tar.bz2"
+  declare desc2="$pkg-$ver2.desc"
+  declare path2=`awk '/^install: / { print $2; exit }' "$tmp_desc"`
+
+  # download new version
+  cp "../mirror/$file2" .
+  # wget -q "$pk_find_desc_mirror/$path2"
+  cp "$tmp_desc" "$desc2"
+
+  # check the md5
+  declare dig1=`cat "$tmp_desc" | awk '/^install: / { print $4; exit }'`
+  declare dig2=`md5sum $file2 | awk '{print $1}'`
+  [ "$dig1" != "$dig2" ] && {
+    echo "ERROR: md5 sum did not match"
+    rm "$file2"
+    rm "$desc2"
+    exit 1
+  }
+
+  # create version file
+  # declare ver_file="$pkg-$ver2.vers"
+  # rm -f "$ver_file"
+  # declare dep
+  # for dep in `pk-print-deps "$tmp_desc"`
+  # do
+  # TODO fix
+  #   declare verd=`pk-print-ver <(pk-find-desc "$dep")`
+  #   echo "$dep" "$verd" >> "$ver_file"
+  # done
+
+  return 0
+}
+
+pk-print-deps()
+{
+  declare deps=`grep 'requires' -`
+  declare deps=${deps#requires:}
+  echo "$deps"
+}
+
+pk-print-ver()
+{
+  awk '/^version: / { print $2; exit }' -
+}
+
+pk-make-dep-list2()
+{
+  declare pkg="$1"
+  declare find_fun="$2"
+  declare check_fun="$3"
+
+  declare tmp_deps=`pk-make-tmp`
+
+  cd "$INSTALL_PATH"
+  add_deps()
+  {
+    declare dep
+    for dep in `"$find_fun" "$1" | pk-print-deps`
+    do
+      grep "$dep" "$MINGW_BASE" >&/dev/null && continue
+      add_deps "$dep"
+    done
+
+    "$check_fun" "$1" && return
+    echo "$1" >> "$tmp_deps"
+  }
+  add_deps "$pkg"
+
+  # find uniq lines without messing with sort
+  awk '!seen[$0]++' "$tmp_deps"
+}
+
+pk-check-package()
+{
+  declare pkg="$1"
+  declare tab="$2"
+
+  declare file=`find . -name "$pkg*.vers"`
+  declare tab2="$tab  "
+
+  declare tmp_diff=`pk-make-tmp`
+
+  declare pkg v1
+  cat "$file" | while read pkg v1
+  do
+    if [[ "$pkg" =~ ^my- ]]
+    then
+      pk-check-package "$pkg" "$tab2" >> "$tmp_diff"
+    else
+      declare v2=`pk-find-desc "$pkg" | pk-print-ver`
+      [ "$v2" == "$v1" ] && continue
+      echo "$tab2$pkg $v1 -> $v2" >> "$tmp_diff"
+    fi
+  done
+  [ -s "$tmp_diff" ] && {
+    echo "$tab$pkg is out-of-date, diff:"
+    cat "$tmp_diff"
+    return 1
+  }
+  return 0
+}
