Refactor pk install and rm scripts
Erase bad use of global variables

diff --git a/bin/cygwin/pk-install b/bin/cygwin/pk-install
--- a/bin/cygwin/pk-install
+++ b/bin/cygwin/pk-install
@@ -10,40 +10,23 @@ on_exit()
 }
 trap 'on_exit' EXIT
 
-PACKAGE="$1"
-DIR="$2"
+package="$1"
+dir=`pk-build-dir "$2"`
 
-[ -z "$PACKAGE" ] && { echo "ERROR: package not specified"; exit 1; }
-pk_set_dir "$DIR"
+[ $dir" != /build" ] && pk-create-local-dirs "$dir"
 
-PACKAGE_NAME=`pk-find-fun "$PACKAGE" "$INSTALL_PATH" "tar.bz2"`
+[ -z "$package" ] && { echo "ERROR: package not specified"; exit 1; }
+name=`pk-find-fun "$package" "$INSTALL_PATH" "tar.bz2"`
 
-# check if package already installed
-[ -f "$LIST_DIR_LOCAL/$PACKAGE_NAME.list" ] && { echo "$PACKAGE_NAME is already installed"; exit 0; };
-
-# make dep list
-cd "$INSTALL_PATH"
 tmp_deps=`mktemp`
-add_deps()
-{
-  declare deps file
-
-  deps=`grep 'requires' "$1.desc"`
-  deps=${deps#requires:}
-
-  for pack in $deps
-  do
-    grep "$pack" "$MINGW_BASE" >&/dev/null && continue
-    add_deps `pk-find-fun "$pack" "$INSTALL_PATH" "desc"`
-  done
-
-  [ -f "$LIST_DIR_LOCAL/$1.list" ] && return
-  echo "$1" >> "$tmp_deps"
-}
-add_deps "$PACKAGE_NAME"
-
-# find uniq lines without messing with sort
-awk '!seen[$0]++' "$tmp_deps" | while read name
+pk-check-installed "$name" "$dir"
+pk-make-dep-list "$name" "$dir" > "$tmp_deps"
+cat "$tmp_deps" | while read name
 do
-  pk-install-job "$name" "$DIR_EXPAND"
+  file="$INSTALL_PATH/$name.tar.bz2"
+  pk-check-clash "$name" "$dir"
+  echo "install $name"
+  pk-extract "$name" "$dir"
+  [ "$dir" != "/build" ] && cp "$INSTALL_PATH/$name.tar.bz2" "$dir/packages"
 done
+
diff --git a/bin/cygwin/pk-rm b/bin/cygwin/pk-rm
--- a/bin/cygwin/pk-rm
+++ b/bin/cygwin/pk-rm
@@ -4,17 +4,22 @@ set -e
 
 . pk-common
 
-PACKAGE="$1"
-DIR="$2"
+package="$1"
+dir=`pk-build-dir "$2"`
 
-[ -z "$PACKAGE" ] && { echo "ERROR: package not specified"; exit 1; }
-pk_set_dir "$DIR"
+build_dir="$dir/"`pk-root-dir "$dir"`
 
-PACKAGE_NAME=`pk-find-fun "$PACKAGE" "$LIST_DIR_LOCAL" "list"`
+[ -z "$package" ] && { echo "ERROR: package not specified"; exit 1; }
 
-echo "remove $PACKAGE_NAME"
+name=`pk-find-fun "$package" "$dir/list" "list"`
 
-LIST_FILE="$LIST_DIR_LOCAL/$PACKAGE_NAME.list"
-cd "$BUILD_PATH_LOCAL"
-rm `cat "$LIST_FILE"`
-rm "$LIST_FILE"
+echo "remove $name"
+
+list_file="$dir/list/$name.list"
+
+cd "$build_dir"
+rm `cat "$list_file"`
+rm "$list_file"
+
+# rm package from local dir if needed
+[ "$dir" != "/build" ] && rm "$dir/packages/$name.tar.bz2"
